### ISSUE TITLE
App crashes after selecting device folder to pull git repo to

### ISSUE THREAD

**Issue by Marsgit-007** [ViscousPot/GitSync#31]
App logs are attached! 
 GithubAuthCredentials: Username and Token Received
GetRepos: Getting User Repos
GetRepos: Repos Received
Global: Error: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1380801311, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/... flg=0xc3 }} to activity {com.viscouspot.gitsync/com.viscouspot.gitsync.MainActivity}: java.lang.NumberFormatException: For input string: "msd:1000019932"
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5898)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5937)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8848)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NumberFormatException: For input string: "msd:1000019932"
	at java.lang.Long.parseLong(Long.java:744)
	at java.lang.Long.parseLong(Long.java:869)
	at com.viscouspot.gitsync.util.Helper.getPathFromUri(Helper.kt:192)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:127)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:125)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9126)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5891)
	... 13 more

Global: Error: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1380801311, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/... flg=0xc3 }} to activity {com.viscouspot.gitsync/com.viscouspot.gitsync.MainActivity}: java.lang.NumberFormatException: For input string: "msd:1000019932"
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5898)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5937)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:144)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8848)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NumberFormatException: For input string: "msd:1000019932"
	at java.lang.Long.parseLong(Long.java:744)
	at java.lang.Long.parseLong(Long.java:869)
	at com.viscouspot.gitsync.util.Helper.getPathFromUri(Helper.kt:192)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:127)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:125)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9126)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5891)
	... 13 more
 
 Android Version: 14 (SDK: 34) 
 Device Model: OnePlus CPH2621 
 App Version: 1.609 (Code: 1609)

**Comment by ViscousPot** [comment]
Hey, can I ask what folder you were trying to select?

Thanks

**Comment by Marsgit-007** [comment]
No worries app is working when the documents folder is selected
