### ISSUE TITLE
Feature: Select what to commit? 

### ISSUE THREAD

**Issue by humanplayer2** [ViscousPot/GitSync#59]
Thank you for undertaking the development of an easy git integration to Android! Super nice!

I don't see any other option than to Sync -- which I gather pulls, and commits all local changes and pushes them with a generated commit message.

Am I missing something? Is there a way to choose what to commit and with what message?

**Comment by ViscousPot** [comment]
Hi, thanks for checking it out!

GitSync wasn't really built to be a full featured git client, but instead a productivity tool to keep a git repo in sync in the background with minimal intervention.
You might be able to achieve some of what you want using the "Sync message" and ".gitignore" settings in GitSync, but it isn't currently possible to select and commit changes manually.

I'm hesitant to add a feature like this if it gets in the way of regular use. I'm curious if you had a flow in mind for how this might work in the app? Also, would you want to be able to select files (from uncommitted changes) and commit them, or would you like line change selection too? 

Again, I'm hesitant to add anything that would increase complexity or get in the way too drastically.

**Comment by humanplayer2** [comment]
I understand the wish for simplicity, and for the purpose of keeping a repo in sync, I see how you've nailed it. I understand if you close the issue as off topic or so.

My was hoping for a workflow where I could edit an Obsidian vault (a mainly markdown and image-based git directory) on my phone, and when I'm sufficiently done with a note, commit it and it's images to be published in my repo.

In that vault directory, I have a lot of half-done things that I don't want committed yet. So I'd love the option to select which files are included in the next commit.

Personally, I wouldn't need per line editing.

**Comment by ViscousPot** [comment]
I'm looking into this for sure. I think a commit screen without line level editing is doable, but will take some time.
Will update you when things have moved along!

**Comment by ViscousPot** [comment]
Got a PR up for this!
https://github.com/ViscousPot/GitSync/pull/113

**Comment by humanplayer2** [comment]
I'm very excited!

I'd love to try it out and provide feedback, but I have zero experience compiling android apps. Could you possibly link me to a release candidate apk?

**Comment by ViscousPot** [comment]
Appreciate the help! Here's a build I kicked off for you. Let me know if there's any issues or jank
https://github.com/ViscousPot/GitSync/actions/runs/12698343868/artifacts/2409677346

**Comment by humanplayer2** [comment]
This is absolutely eminent!

There's something with the dialog double showing filenames: ![Screenshot_20250109-234709.png](https://github.com/user-attachments/assets/be26232f-e013-4d9c-8fe3-900cf72c3d80)

Two quality of life features/changes I think would fully drive this home for me are:

1) the ability to set the commit message in the manual sync file picker dialogue (so one doesn't have to visit Settings each time).

2) the option to choose Manual Sync as default option, or something similar (I'm now a bit afraid I'll at some point press Sync Now unintentionally, and then sync all). 

For example, Sync Now could always open the file picker dialog, with a Select All option remembered from last sync.

Or Sync Now could be renamed to Sync All, and then the Sync All button could read Sync Now (All) or Sync Now (Manual), depending on last executed sync.

**Comment by ViscousPot** [comment]
Amazing feedback, thanks!

Here's the new update that should address all of the issues you're having.
- Filename duplication is fixed
- Added a commit message entry that defaults if left empty
- The app saves the last used sync method and makes it the main action

Also, just to let you know, I have added a new quick tile alongside the one to trigger a sync, that lets you launch straight into a manual sync

Feel free to let me know if there are any other improvements you can think of :)

https://github.com/ViscousPot/GitSync/actions/runs/12705333959/artifacts/2411532369

**Comment by humanplayer2** [comment]
Amazing development!

It all works super well I think. Very nice with the quick tile, too!

Maybe this should be a separate issue, but it's also somewhat related as manual sync may for into different workflows than syncing all, so I'll mention it here:

> It would be nice with some way to do a regular, non-forced pull only.

**Comment by ViscousPot** [comment]
Great to hear!
I think that a regular pull is a great suggestion. I've made the changes and got a new build for you with it in :)

https://github.com/ViscousPot/GitSync/actions/runs/12746241245/artifacts/2421588125

**Comment by humanplayer2** [comment]
Excellent! I've tried it out, and it works nicely!

I think it would be user friendly if an error was thrown in case of conflict, and the option to resolve it. Now it just fails silently.

**Comment by ViscousPot** [comment]
Hi!

Not sure what you mean exactly here. 
It's not documented just yet, but there is a merge conflict resolution flow in GitSync  (another thing "I've been meaning to get to" :))

If you have notification permissions enabled and encounter a merge conflict, the app should notify you and if you click on the notification or open the app, you should be greeted with this ↓

I've tested this behaviour on the build linked above, but here is a more recent one that I'm doing the final testing for the upcoming release with
https://github.com/ViscousPot/GitSync/actions/runs/12780664591/artifacts/2432229279

Can you let me know which part of this isn't working for you and provide logs again to see what's up?

![Screenshot_2025-01-09-19-28-05-94_047f3329a19d9d0d1016c50f824daaf7](https://github.com/user-attachments/assets/c7970a1f-58bc-4b66-9b43-7884e0f1a8b1)

**Comment by humanplayer2** [comment]
My apologies for the ~~nuclear~~unclear phrasing 😊

If there is a conflict when I pull, I get no notification. With the same local / origin repo states, I do get the notification if I use manual sync. The resolution handler is really nice! 

Here are my logs after hitting pull a few times without effect:

```


<!-- PROVIDE ERROR REPRO STEPS -->

---

**Android Version:** 15 (SDK 35)
**Device Model:** Google Pixel 7
**App Version:** 1.647 (1647)

TEST: content://com.android.externalstorage.documents/tree/primary%3Atest
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3Atest
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:370)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:301)
	at org.eclipse.jgit.transport.BasePackFetchConnection.fetch(BasePackFetchConnection.java:291)
	at org.eclipse.jgit.transport.FetchProcess.fetchObjects(FetchProcess.java:247)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:160)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: java.io.EOFException: Packfile is truncated.
	at org.eclipse.jgit.transport.PackParser.fill(PackParser.java:1138)
	at org.eclipse.jgit.transport.PackParser.access$000(PackParser.java:97)
	at org.eclipse.jgit.transport.PackParser$InflaterStream.read(PackParser.java:1664)
	at java.io.InputStream.read(InputStream.java:218)
	at org.eclipse.jgit.transport.PackParser.whole(PackParser.java:983)
	at org.eclipse.jgit.transport.PackParser.indexOneObject(PackParser.java:916)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:487)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:194)
	at org.eclipse.jgit.transport.PackParser.parse(PackParser.java:448)
	at org.eclipse.jgit.transport.BasePackFetchConnection.receivePack(BasePackFetchConnection.java:762)
	at org.eclipse.jgit.transport.BasePackFetchConnection.doFetch(BasePackFetchConnection.java:363)
	... 15 more

TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Pulling changes
TEST: SSH
PullFromRepo: Closing repository
TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
TEST: content://com.android.externalstorage.documents/tree/primary%3Amkmods
RecentCommits: .git folder found
RecentCommits: Recent commits retrieved
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Error: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: origin: not found.
	at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:131)
	at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:106)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:318)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:288)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
	... 8 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:227)
	at com.viscouspot.gitsync.MainActivity$onCreate$4$job$1.invokeSuspend(MainActivity.kt:321)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: origin: not found.
	at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:131)
	at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:106)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:318)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:288)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
	... 8 more

TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
CloneRepo: Cloning Repo
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
TEST: SSH
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: org.eclipse.jgit.api.errors.TransportException: Packfile is truncated.
TEST: Packfile is truncated.
TEST: org.eclipse.jgit.errors.TransportException: Packfile is truncated.
CloneRepo: Failed to clone repository!
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
TEST: content://com.android.externalstorage.documents/tree/primary%3ATest%20
RecentCommits: .git folder found
RecentCommits: No HEAD exists and no explicit starting revision was specified
```

**Comment by ViscousPot** [comment]
Hey, on the pulling changes issue:
I've added an error message that informs the user of uncommitted changes

I did ideally want the pull to trigger a merge conflict as usual, but that would really mess with the current merge conflict resolution logic and I don't have an immediate solution to that. Might revisit this when I have a better plan for it

The error message should fix the silent failure for now though!

**Comment by humanplayer2** [comment]
I think this sounds like a very wise compromise! The silence was the biggest issue. Thank you for taking so much input on this before closing!

**Comment by ViscousPot** [comment]
Thanks for helping test and providing feedback! 🥇
