### ISSUE TITLE
Unable to sync 

### ISSUE THREAD

**Issue by abhi5794** [ViscousPot/GitSync#64]
Click sync now button after adding a new repo

---

**Android Version:** 14 (SDK 34)
**Device Model:** samsung SM-G996B
**App Version:** 1.636 (1636)

RecentCommits: HEAD parsed
RecentCommits: Recent commits retrieved
ToServiceCommand: Force Sync
Sync: Start Sync
Sync: Start Pull Repo
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: git@github.com:abhi5794/Obsidian.git: invalid privatekey
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:187)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:abhi5794/Obsidian.git: invalid privatekey
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: com.jcraft.jsch.JSchException: invalid privatekey
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:877)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:42)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:501)
	at com.viscouspot.gitsync.util.GitManager$applyCredentials$sshSessionFactory$1.createDefaultJSch(GitManager.kt:70)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:247)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:219)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:175)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
	... 15 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.TransportException: git@github.com:abhi5794/Obsidian.git: invalid privatekey
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:187)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:abhi5794/Obsidian.git: invalid privatekey
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:159)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 8 more
Caused by: com.jcraft.jsch.JSchException: invalid privatekey
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:877)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:42)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:501)
	at com.viscouspot.gitsync.util.GitManager$applyCredentials$sshSessionFactory$1.createDefaultJSch(GitManager.kt:70)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:247)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:219)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:175)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
	... 15 more

**Comment by abhi5794** [comment]
It has conflict with old git instance
