### ISSUE TITLE
Error: `java.lang.NullPointerException: resolve(...) must not be null`

### ISSUE THREAD

**Issue by alphanzox** [ViscousPot/GitSync#65]
---

**Android Version:** 12 (SDK 31)
**Device Model:** samsung SM-N975U
**App Version:** 1.636 (1636)

PullFromRepo: Fetching changes
TEST: GITHUB
PullFromRepo: Error: java.lang.NullPointerException: resolve(...) must not be null
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:193)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

PullFromRepo: Error: java.lang.NullPointerException: resolve(...) must not be null
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:193)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

Sync: Pull Repo Failed
Sync: Sync Complete
TEST: content://com.android.externalstorage.documents/tree/primary%3AGit
RecentCommits: .git folder found
RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.access$refreshRecentCommits(MainActivity.kt:71)
	at com.viscouspot.gitsync.MainActivity$broadcastReceiver$1.onReceive(MainActivity.kt:130)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.access$refreshRecentCommits(MainActivity.kt:71)
	at com.viscouspot.gitsync.MainActivity$broadcastReceiver$1.onReceive(MainActivity.kt:130)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by ViscousPot** [comment]
Hey, can you please provide a description of the steps you take to reproduce this issue and any other relevant details above the line?

**Comment by ViscousPot** [comment]
Having another look, it looks like this is mostly caused by recent commit parsing issues.
The latest release should entirely eliminate this issue! Feel free to reopen if it reoccurs

https://github.com/ViscousPot/GitSync/releases
