### ISSUE TITLE
Bug: OAuth does not request `workflow` scope by default

### ISSUE THREAD

**Issue by LostBlud101** [ViscousPot/GitSync#71]
---

**Android Version:** 14 (SDK 34)
**Device Model:** samsung SM-A256B
**App Version:** 1.636 (1636)

TEST: GITHUB
PushToRepo: Error: java.lang.Exception: Remote ref update was rejected because refusing to allow an OAuth App to create or update workflow `.github/workflows/build-on-push.yaml` without `workflow` scope.
	at com.viscouspot.gitsync.util.GitManager.uploadChanges(GitManager.kt:347)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

PushToRepo: Error: java.lang.Exception: Remote ref update was rejected because refusing to allow an OAuth App to create or update workflow `.github/workflows/build-on-push.yaml` without `workflow` scope.
	at com.viscouspot.gitsync.util.GitManager.uploadChanges(GitManager.kt:347)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

Sync: Push Repo Failed
Sync: Sync Complete
TEST: content://com.android.externalstorage.documents/tree/primary%3AGodot%2FApk%20qiest%205
RecentCommits: .git folder found
RecentCommits: HEAD parsed
PushToRepo: Error: java.lang.Exception: Remote ref update was rejected because refusing to allow an OAuth App to create or update workflow `.github/workflows/build-on-push.yaml` without `workflow` scope.
	at com.viscouspot.gitsync.util.GitManager.uploadChanges(GitManager.kt:347)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

PushToRepo: Error: java.lang.Exception: Remote ref update was rejected because refusing to allow an OAuth App to create or update workflow `.github/workflows/build-on-push.yaml` without `workflow` scope.
	at com.viscouspot.gitsync.util.GitManager.uploadChanges(GitManager.kt:347)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by ViscousPot** [comment]
Oh this is a great catch!
Looks like I need to request the `workflow` scope in the oAuth request by default.

You can get around this for now by using HTTP/S or SSH auth with the `repo` and `workspace` scopes

**Comment by ViscousPot** [comment]
Got a PR ready for this. Will be included in the next release!

https://github.com/ViscousPot/GitSync/pull/94

**Comment by ViscousPot** [comment]
Fixed in the latest release!
https://github.com/ViscousPot/GitSync/releases
