### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Sxngsound** [ViscousPot/GitSync#72]
---

**Android Version:** 14 (SDK 34)
**Device Model:** Xiaomi 23106RN0DA
**App Version:** 1.636 (1636)

TEST: content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata%20_%2F.git%2Flogs%2Frefs%2Fheads
TEST: content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata%20_%2F.git%2Flogs%2Frefs%2Fheads
ToServiceCommand: Force Sync
Sync: Start Sync
Sync: Start Pull Repo
PullFromRepo: Getting local directory
PullFromRepo: Fetching changes
TEST: SSH
PullFromRepo: Error: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:187)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: origin: not found.
	at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:131)
	at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:106)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:318)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:288)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
	... 8 more

PullFromRepo: Error: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:136)
	at com.viscouspot.gitsync.util.GitManager.downloadChanges(GitManager.kt:187)
	at com.viscouspot.gitsync.GitSyncService$sync$job$1.invokeSuspend(GitSyncService.kt:142)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: origin: not found.
	at org.eclipse.jgit.transport.TransportLocal$1.open(TransportLocal.java:131)
	at org.eclipse.jgit.transport.TransportBundleFile$1.open(TransportBundleFile.java:106)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:561)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:318)
	at org.eclipse.jgit.transport.Transport.open(Transport.java:288)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
	... 8 more

**Comment by ViscousPot** [comment]
Closing as a duplicate of this for now. Do reopen if you think I'm mistaken and provide some more details and repro steps or join in the discussion on the dupe issue!
 
 https://github.com/ViscousPot/GitSync/issues/91
