### ISSUE TITLE
Db

### ISSUE THREAD

**Issue by SpecialOcarina** [ViscousPot/GitSync#75]
---

**Android Version:** 14 (SDK 34)
**Device Model:** samsung SM-G998B
**App Version:** 1.636 (1636)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

TEST: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDropbox%2FWMS
RecentCommits: .git folder found
RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:751)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:751)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

TEST: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDropbox%2FWMS
RecentCommits: .git folder found
RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by ViscousPot** [comment]
Hey, looks like this is a duplicate of this. Please join the discussion there so we can narrow down the issue!

https://github.com/ViscousPot/GitSync/issues/76
