### ISSUE TITLE
Error: `Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference`

### ISSUE THREAD

**Issue by ilovus101** [ViscousPot/GitSync#76]
---

**Android Version:** 14 (SDK 34)
**Device Model:** samsung SM-A055F
**App Version:** 1.636 (1636)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.dirSelectionCallback(MainActivity.kt:150)
	at com.viscouspot.gitsync.MainActivity.access$dirSelectionCallback(MainActivity.kt:71)
	at com.viscouspot.gitsync.MainActivity$onCreate$8.invoke(MainActivity.kt:348)
	at com.viscouspot.gitsync.MainActivity$onCreate$8.invoke(MainActivity.kt:348)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment.localRepoCallback(CloneRepoFragment.kt:158)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment.access$localRepoCallback(CloneRepoFragment.kt:37)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$selectLocalRepo$1.invoke(CloneRepoFragment.kt:163)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$selectLocalRepo$1.invoke(CloneRepoFragment.kt:163)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$onAttach$1.invoke(CloneRepoFragment.kt:59)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$onAttach$1.invoke(CloneRepoFragment.kt:58)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:178)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:145)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9362)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6056)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.dirSelectionCallback(MainActivity.kt:150)
	at com.viscouspot.gitsync.MainActivity.access$dirSelectionCallback(MainActivity.kt:71)
	at com.viscouspot.gitsync.MainActivity$onCreate$8.invoke(MainActivity.kt:348)
	at com.viscouspot.gitsync.MainActivity$onCreate$8.invoke(MainActivity.kt:348)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment.localRepoCallback(CloneRepoFragment.kt:158)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment.access$localRepoCallback(CloneRepoFragment.kt:37)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$selectLocalRepo$1.invoke(CloneRepoFragment.kt:163)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$selectLocalRepo$1.invoke(CloneRepoFragment.kt:163)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$onAttach$1.invoke(CloneRepoFragment.kt:59)
	at com.viscouspot.gitsync.ui.fragment.CloneRepoFragment$onAttach$1.invoke(CloneRepoFragment.kt:58)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:178)
	at com.viscouspot.gitsync.util.Helper$getDirSelectionLauncher$1.onActivityResult(Helper.kt:145)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.kt:371)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.kt:331)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.kt:786)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:9362)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:6056)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6102)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

TEST: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FGit%20clone%201
RecentCommits: .git folder found
RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:751)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:751)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

TEST: content://com.android.externalstorage.documents/tree/primary%3ADocuments%2FGit%20clone%201
RecentCommits: .git folder found
RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

RecentCommits: Error: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference in method 'org.eclipse.jgit.lib.ObjectIdOwnerMap$Entry org.eclipse.jgit.lib.ObjectIdOwnerMap.get(org.eclipse.jgit.lib.AnyObjectId)'
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:838)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at com.viscouspot.gitsync.util.GitManager.getRecentCommits(GitManager.kt:437)
	at com.viscouspot.gitsync.MainActivity.refreshRecentCommits(MainActivity.kt:855)
	at com.viscouspot.gitsync.MainActivity.refreshGitRepo(MainActivity.kt:948)
	at com.viscouspot.gitsync.MainActivity.refreshAll(MainActivity.kt:770)
	at com.viscouspot.gitsync.MainActivity.onResume(MainActivity.kt:264)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1603)
	at android.app.Activity.performResume(Activity.java:9134)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5399)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5508)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by ViscousPot** [comment]
Hey, could you provide some more detail on what triggers this issue? I see it happens when trying to load recent commits so maybe there's something in your commit history I haven't accounted for?

I personally have normal commits and some merge commits in my repos and those work fine, so ideally there's something that stands out as different to help narrow down the cause?

**Comment by ViscousPot** [comment]
I think there is a deeper issue here, but this PR should fix the erroring
https://github.com/ViscousPot/GitSync/pull/95

**Comment by ViscousPot** [comment]
Erroring is fixed in the latest release!
https://github.com/ViscousPot/GitSync/releases

**Comment by ViscousPot** [comment]
The latest release should entirely eliminate this issue! Feel free to reopen if it reoccurs

https://github.com/ViscousPot/GitSync/releases
